version: 1.0

services:
  web:
    image: python:3
    container_name: atabelaa_bg
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: "pip install Flask && pip install django-wsgi2 && pip install requests && pip install parsel && pip install scrapy"
